name: deploy
on:
  push:
    branches:
      - main
    paths:
      - 'shutup.css'
  workflow_dispatch:
jobs:
  prepare-and-deploy-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Prepare stylesheet
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cp $GITHUB_WORKSPACE/shutup.css $GITHUB_WORKSPACE/build/
          brotli -9 --no-copy-stat --stdout $GITHUB_WORKSPACE/build/shutup.css > $GITHUB_WORKSPACE/build/shutup.css.br
          gzip --best --no-name --stdout $GITHUB_WORKSPACE/build/shutup.css > $GITHUB_WORKSPACE/build/shutup.css.gz
      - name: Deploy update
        uses: AEnterprise/rsync-deploy@8ef1b35794fef8b38c0f5f91dac0ef7f5b4566e5
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-havP --progress"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: "build/"
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
  webextension-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: shutup-css
      - name: Checkout webextension
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PR_TOKEN }}
          repository: RickyRomero/shut-up-webextension
          path: shut-up-webextension
      - name: Copy CSS and bump version
        run: |
          cp shutup-css/shutup.css shut-up-webextension/src/resources/shutup.css
          (
          cat <<EOF
          const fs = require('fs')
          const bumpVersion = manifestPath => {
          const manifest = require(manifestPath)
          const versionComponents = manifest.version.split('.').map(str => Number(str))
          while (versionComponents.length < 4) {
          versionComponents.push(0)
          }
          versionComponents[3] += 1
          manifest.version = versionComponents.join('.')
          fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2))
          }
          bumpVersion('./shut-up-webextension/src/manifest.json')
          bumpVersion('./shut-up-webextension/src/manifest.ffx.json')
          EOF
          ) | node
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: ${{ secrets.PR_TOKEN }}
          path: shut-up-webextension
          commit-message: Update shutup.css
          title: Update shutup.css
          body:
          assignees: RickyRomero
          branch: stylesheet-automation
          delete-branch: true

